baseURL: "/"
title: Milly Wrote-it
theme: mini

pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
paginate: 10
permalinks:
  posts: /posts/:slug/

social:
  # e.g.
  github: https://github.com/millyrowboat
  twitter: https://twitter.com/millyrowboat

params:
  author: Milly Rowett
  # Author biography
  bio: Currently learning in public how to be an Engineering Manager. Updates twice monthly (maybe).
  # Site Description, used in HTML meat
  description: Musings on management and engineering
  copyright: '© Milly Rowett 2022'
  showPowerBy: false
  customCSS:
    - css/custom.css # local css in `static/css/custom.css`

