baseURL: "/"
title: Milly Wrote-it
theme: 
   - github.com/nodejh/hugo-theme-mini

pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
paginate: 3
permalinks:
  posts: /posts/:title/

social:
  # e.g.
  github: https://github.com/millyrowboat
  twitter: https://twitter.com/millyrowboat

params:
  author: Milly Rowett
  # Author biography
  bio: Engineering Manager
  # Site Description, used in HTML meat
  description: Musings on management and engineering
  copyright: ' '
  showPowerBy: false

