baseURL: "/"
title: Milly Wrote-it
theme: mini

pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
paginate: 3
permalinks:
  posts: /posts/:title/

social:
  # e.g.
  github: https://github.com/millyrowboat
  twitter: https://twitter.com/millyrowboat

params:
  author: Milly Rowett
  # Author biography
  bio: Currently learning in public how to be an Engineering Manager
  # Site Description, used in HTML meat
  description: Musings on management and engineering
  copyright: ' '
  showPowerBy: false
  customCSS:
    - css/custom.css # local css in `static/css/custom.css`

